export const countryOptions = [
  { label: "Afghanistan", value: "US", image: "/flags/afg.png", cur: "ANA" },
  {
    label: "Albania",
    value: "US",
    image: "/flags/flag-for-albania.png",
    cur: "ALL",
  },
  {
    label: "Algeria",
    value: "US",
    image: "/flags/flag-for-algeria.png",
    cur: "DZD",
  },
  {
    label: "Andorra",
    value: "US",
    image: "/flags/flag-for-andorra.png",
    cur: "€",
  },
  {
    label: "Angola",
    value: "US",
    image: "/flags/flag-for-angola.png",
    cur: "AOA",
  },
  {
    label: "Antigua And Barbuda",
    value: "US",
    image: "/flags/flag-for-antigua-and-barbuda.png",
    cur: "$",
  },
  {
    label: "Argentina",
    value: "US",
    image: "/flags/flag-for-argentina.png",
    cur: "$",
  },
  {
    label: "Armenia",
    value: "US",
    image: "/flags/emojione_flag-for-armenia.png",
    cur: "AMD",
  },
  {
    label: "Australia ",
    value: "US",
    image: "/flags/emojione_flag-for-australia.png",
    cur: "A$",
  },
  {
    label: "Austria ",
    value: "US",
    image: "/flags/emojione_flag-for-austria.png",
    cur: "€",
  },
  {
    label: "Azerbaijan ",
    value: "US",
    image: "/flags/emojione_flag-for-azerbaijan.png",
    cur: "AZN",
  },
  {
    label: "Bahamas ",
    value: "US",
    image: "/flags/emojione_flag-for-bahamas.png",
    cur: "B$",
  },
  {
    label: "Bahrain ",
    value: "US",
    image: "/flags/emojione_flag-for-bahrain.png",
    cur: "BD",
  },
  {
    label: "Bangladesh ",
    value: "US",
    image: "/flags/emojione_flag-for-bangladesh.png",
    cur: "৳",
  },
  {
    label: "Barbados ",
    value: "US",
    image: "/flags/emojione_flag-for-barbados.png",
    cur: "BBD",
  },
  {
    label: "Belarus ",
    value: "US",
    image: "/flags/emojione_flag-for-belarus.png",
    cur: "BYN",
  },
  {
    label: "Belgium ",
    value: "US",
    image: "/flags/emojione_flag-for-belgium.png",
    cur: "€",
  },
  {
    label: "Belize ",
    value: "US",
    image: "/flags/emojione_flag-for-belize.png",
    cur: "$",
  },
  {
    label: "Benin ",
    value: "US",
    image: "/flags/emojione_flag-for-benin.png",
    cur: "CFA",
  },
  {
    label: "Bhutan ",
    value: "US",
    image: "/flags/emojione_flag-for-bhutan.png",
    cur: "BTN",
  },
  {
    label: "Bolivia ",
    value: "US",
    image: "/flags/emojione_flag-for-bolivia.png",
    cur: "BOB",
  },
  {
    label: "Bosnia & Herzegovina ",
    value: "US",
    image: "/flags/emojione_flag-for-bosnia-and-herzegovina.png",
    cur: "KM",
  },
  {
    label: "Botswana ",
    value: "US",
    image: "/flags/emojione_flag-for-botswana.png",
    cur: "BWP",
  },
  {
    label: "Brazil ",
    value: "US",
    image: "/flags/emojione_flag-for-brazil.png",
    cur: "BRL",
  },
  {
    label: "Brunei Darussalam ",
    value: "US",
    image: "/flags/emojione_flag-for-brunei.png",
    cur: "B$",
  },
  {
    label: "Bulgarian Lev ",
    value: "US",
    image: "/flags/emojione_flag-for-bulgaria.png",
    cur: "BGN",
  },
  {
    label: "Burkina Faso ",
    value: "US",
    image: "/flags/emojione_flag-for-burkina-faso.png",
    cur: "CFA",
  },
  {
    label: "Burundi ",
    value: "US",
    image: "/flags/emojione_flag-for-burundi.png",
    cur: "BIF",
  },
  {
    label: "Cabo Verde ",
    value: "US",
    image: "/flags/emojione_flag-for-cape-verde.png",
    cur: "CVE",
  },
  {
    label: "Cambodia ",
    value: "US",
    image: "/flags/emojione_flag-for-cambodia.png",
    cur: "KHR",
  },
  {
    label: "Cameroon ",
    value: "US",
    image: "/flags/emojione_flag-for-cameroon.png",
    cur: "CFA",
  },
  {
    label: "Canada ",
    value: "US",
    image: "/flags/emojione_flag-for-canada.png",
    cur: "$",
  },
  {
    label: "Central African Republics ",
    value: "US",
    image: "/flags/emojione_flag-for-central-african-republic.png",
    cur: "CFA",
  },
  {
    label: "Chad ",
    value: "US",
    image: "/flags/emojione_flag-for-chad.png",
    cur: "CFA",
  },
  {
    label: "Chile ",
    value: "US",
    image: "/flags/emojione_flag-for-chile.png",
    cur: "$",
  },
  {
    label: "China ",
    value: "US",
    image: "/flags/emojione_flag-for-china.png",
    cur: "¥",
  },
  {
    label: "Colombia ",
    value: "US",
    image: "/flags/emojione_flag-for-colombia.png",
    cur: "COP",
  },
  {
    label: "Comoros ",
    value: "US",
    image: "/flags/emojione_flag-for-comoros.png",
    cur: "KMF",
  },
  {
    label: "Costa Rica ",
    value: "US",
    image: "/flags/emojione_flag-for-costa-rica.png",
    cur: "₡",
  },
  {
    label: "Croatia ",
    value: "US",
    image: "/flags/emojione_flag-for-croatia.png",
    cur: "€",
  },
  {
    label: "Cuba ",
    value: "US",
    image: "/flags/emojione_flag-for-cuba.png",
    cur: "CUP",
  },
  {
    label: "Cyprus ",
    value: "US",
    image: "/flags/emojione_flag-for-cyprus.png",
    cur: "€",
  },
  {
    label: "Czech Republic ",
    value: "US",
    image: "/flags/emojione_flag-for-czechia.png",
    cur: "CZK",
  },
  {
    label: "Cote d’lvoire ",
    value: "US",
    image: "/flags/emojione_flag-for-cote-divoire.png",
    cur: "XOF",
  },
  {
    label: "Democratic Republic of Congo ",
    value: "US",
    image: "/flags/emojione_flag-for-congo-kinshasa.png",
    cur: "CDF",
  },
  {
    label: "Denmark ",
    value: "US",
    image: "/flags/emojione_flag-for-denmark.png",
    cur: "Kr",
  },
  {
    label: "Djibouti ",
    value: "US",
    image: "/flags/emojione_flag-for-djibouti.png",
    cur: "DJF",
  },
  {
    label: "Dominica ",
    value: "US",
    image: "/flags/emojione_flag-for-dominican-republic.png",
    cur: "RD$",
  },
  {
    label: "Dominican Republic ",
    value: "US",
    image: "/flags/emojione_flag-for-bhutan.png",
    cur: "RD$",
  },
  {
    label: "Ecuador ",
    value: "US",
    image: "/flags/emojione_flag-for-ecuador.png",
    cur: "$",
  },
  {
    label: "Egypt ",
    value: "US",
    image: "/flags/emojione_flag-for-egypt.png",
    cur: "E£",
  },
  {
    label: "EI Salvador ",
    value: "US",
    image: "/flags/emojione_flag-for-el-salvador.png",
    cur: "₡",
  },
  {
    label: "Equatorial Guinea ",
    value: "US",
    image: "/flags/emojione_flag-for-equatorial-guinea.png",
    cur: "FCFA",
  },
  {
    label: "Eritrea ",
    value: "US",
    image: "/flags/emojione_flag-for-eritrea.png",
    cur: "Nfk",
  },
  {
    label: "Estonia ",
    value: "US",
    image: "/flags/emojione_flag-for-estonia.png",
    cur: "KR",
  },
  {
    label: "Ethiopia ",
    value: "US",
    image: "/flags/emojione_flag-for-ethiopia.png",
    cur: "Br",
  },
  {
    label: "Fiji ",
    value: "US",
    image: "/flags/emojione_flag-for-fiji.png",
    cur: "FJ$",
  },
  {
    label: "Finland ",
    value: "US",
    image: "/flags/emojione_flag-for-finland.png",
    cur: "ANA",
  },
  {
    label: "France ",
    value: "US",
    image: "/flags/emojione_flag-for-france.png",
    cur: "€",
  },
  {
    label: "Gabon ",
    value: "US",
    image: "/flags/emojione_flag-for-gabon.png",
    cur: "FCFA",
  },
  {
    label: "Gambia ",
    value: "US",
    image: "/flags/emojione_flag-for-gambia.png",
    cur: "GMD",
  },
  {
    label: "Georgia ",
    value: "US",
    image: "/flags/emojione_flag-for-georgia.png",
    cur: "GEL",
  },
  {
    label: "Germany ",
    value: "US",
    image: "/flags/emojione_flag-for-germany.png",
    cur: "€",
  },
  {
    label: "Ghana ",
    value: "US",
    image: "/flags/emojione_flag-for-ghana.png",
    cur: "GH¢",
  },
  {
    label: "Greece ",
    value: "US",
    image: "/flags/emojione_flag-for-greece.png",
    cur: "€",
  },
  {
    label: "Grenada ",
    value: "US",
    image: "/flags/emojione_flag-for-grenada.png",
    cur: "$",
  },
  {
    label: "Guatemala ",
    value: "US",
    image: "/flags/emojione_flag-for-guatemala.png",
    cur: "GTQ",
  },
  {
    label: "Guernsey ",
    value: "US",
    image: "/flags/emojione_flag-for-guernsey.png",
    cur: "£",
  },
  {
    label: "Guinea ",
    value: "US",
    image: "/flags/emojione_flag-for-guinea.png",
    cur: "GNF",
  },
  {
    label: "Guinea-Bissau ",
    value: "US",
    image: "/flags/emojione_flag-for-guinea-bissau.png",
    cur: "CFA",
  },
  {
    label: "Guyana",
    value: "US",
    image: "/flags/emojione_flag-for-guyana.png",
    cur: "GYD",
  },
  {
    label: "Haiti",
    value: "US",
    image: "/flags/emojione_flag-for-haiti.png",
    cur: "HTG",
  },
  {
    label: "Honduras",
    value: "US",
    image: "/flags/emojione_flag-for-honduras.png",
    cur: "HNL",
  },
  {
    label: "Hong Kong",
    value: "US",
    image: "/flags/emojione_flag-for-hong-kong-sar-china.png",
    cur: "HK$",
  },
  {
    label: "Hungary",
    value: "US",
    image: "/flags/emojione_flag-for-hungary.png",
    cur: "Ft",
  },
  {
    label: "Iceland",
    value: "US",
    image: "/flags/emojione_flag-for-iceland.png",
    cur: "Íkr",
  },
  {
    label: "India",
    value: "US",
    image: "/flags/emojione_flag-for-india.png",
    cur: "₹",
  },
  {
    label: "Indonesia",
    value: "US",
    image: "/flags/emojione_flag-for-indonesia.png",
    cur: "Rp",
  },
  {
    label: "Iran",
    value: "US",
    image: "/flags/emojione_flag-for-iran.png",
    cur: "IRR",
  },
  {
    label: "Iraq",
    value: "US",
    image: "/flags/emojione_flag-for-iraq.png",
    cur: "IQD",
  },
  {
    label: "Ireland",
    value: "US",
    image: "/flags/emojione_flag-for-ireland.png",
    cur: "€",
  },
  {
    label: "Israel",
    value: "US",
    image: "/flags/emojione_flag-for-israel.png",
    cur: "₪",
  },
  {
    label: "Italy",
    value: "US",
    image: "/flags/emojione_flag-for-italy.png",
    cur: "€",
  },
  {
    label: "Jamaica",
    value: "US",
    image: "/flags/emojione_flag-for-jamaica.png",
    cur: "JMD",
  },
  {
    label: "Japan",
    value: "US",
    image: "/flags/emojione_flag-for-japan.png",
    cur: "¥",
  },
  {
    label: "Jordan",
    value: "US",
    image: "/flags/emojione_flag-for-jordan.png",
    cur: "JOD",
  },
  {
    label: "Kazakhstan",
    value: "US",
    image: "/flags/emojione_flag-for-kazakhstan.png",
    cur: "₸",
  },
  {
    label: "Kenya",
    value: "US",
    image: "/flags/emojione_flag-for-kenya.png",
    cur: "Ksh",
  },
  {
    label: "Kiribati",
    value: "US",
    image: "/flags/emojione_flag-for-kiribati.png",
    cur: "AUD",
  },
  {
    label: "Korea",
    value: "US",
    image: "/flags/emojione_flag-for-north-korea.png",
    cur: "₩",
  },
  {
    label: "Kuwait",
    value: "US",
    image: "/flags/emojione_flag-for-kuwait.png",
    cur: "KWD",
  },
  {
    label: "Kyrgyzstan",
    value: "US",
    image: "/flags/emojione_flag-for-kyrgyzstan.png",
    cur: "Лв",
  },
  {
    label: "Lao People’s Democratic Republic",
    value: "US",
    image: "/flags/emojione_flag-for-laos.png",
    cur: "₭N",
  },
  {
    label: "Latvia",
    value: "US",
    image: "/flags/emojione_flag-for-latvia.png",
    cur: "LVL",
  },
  {
    label: "Lebanon",
    value: "US",
    image: "/flags/emojione_flag-for-lebanon.png",
    cur: "LBP",
  },
  {
    label: "Lesotho",
    value: "US",
    image: "/flags/emojione_flag-for-lesotho.png",
    cur: "LSL",
  },
  {
    label: "Liberia",
    value: "US",
    image: "/flags/emojione_flag-for-liberia.png",
    cur: "L$",
  },
  {
    label: "Libya",
    value: "US",
    image: "/flags/emojione_flag-for-libya.png",
    cur: "LYD",
  },
  {
    label: "Liechtenstein",
    value: "US",
    image: "/flags/emojione_flag-for-liechtenstein.png",
    cur: "CHF",
  },
  {
    label: "Lithuania",
    value: "US",
    image: "/flags/emojione_flag-for-lithuania.png",
    cur: "EUR",
  },
  {
    label: "Luxembourg",
    value: "US",
    image: "/flags/emojione_flag-for-luxembourg.png",
    cur: "LUF",
  },
  {
    label: "Macedonia",
    value: "US",
    image: "/flags/emojione_flag-for-macedonia.png",
    cur: "MKD",
  },
  {
    label: "Madagascar",
    value: "US",
    image: "/flags/emojione_flag-for-madagascar.png",
    cur: "Ar",
  },
  {
    label: "Malawi",
    value: "US",
    image: "/flags/emojione_flag-for-malawi.png",
    cur: "MK",
  },
  {
    label: "Malaysia",
    value: "US",
    image: "/flags/emojione_flag-for-malaysia.png",
    cur: "MYR",
  },
  {
    label: "Mauritania",
    value: "US",
    image: "/flags/emojione_flag-for-mauritania.png",
    cur: "MRU",
  },
  {
    label: "Mauritius",
    value: "US",
    image: "/flags/emojione_flag-for-mauritius.png",
    cur: "MUR",
  },
  {
    label: "Mexico",
    value: "US",
    image: "/flags/emojione_flag-for-mexico.png",
    cur: "Mex$",
  },
  {
    label: "Micronesia",
    value: "US",
    image: "/flags/emojione_flag-for-micronesia.png",
    cur: "$",
  },
  {
    label: "Moldova",
    value: "US",
    image: "/flags/emojione_flag-for-moldova.png",
    cur: "MDL",
  },
  {
    label: "Myanmar",
    value: "US",
    image: "/flags/emojione_flag-for-myanmar.png",
    cur: "MMK",
  },
  {
    label: "Namibia",
    value: "US",
    image: "/flags/emojione_flag-for-namibia.png",
    cur: "N$",
  },
  {
    label: "Nauru",
    value: "US",
    image: "/flags/emojione_flag-for-nauru.png",
    cur: "A$",
  },
  {
    label: "Nepal",
    value: "US",
    image: "/flags/emojione_flag-for-nepal.png",
    cur: "NPR",
  },
  {
    label: "Netherlands",
    value: "US",
    image: "/flags/emojione_flag-for-netherlands.png",
    cur: "EUR",
  },
  {
    label: "New Zealand",
    value: "US",
    image: "/flags/emojione_flag-for-new-zealand.png",
    cur: "$",
  },
  {
    label: "Nicaragua",
    value: "US",
    image: "/flags/emojione_flag-for-nicaragua.png",
    cur: "C$",
  },
  {
    label: "Niger",
    value: "US",
    image: "/flags/emojione_flag-for-niger.png",
    cur: "CFA",
  },
  {
    label: "Nigeria",
    value: "US",
    image: "/flags/emojione_flag-for-nigeria.png",
    cur: "₦",
  },
  {
    label: "Norway",
    value: "US",
    image: "/flags/emojione_flag-for-norway.png",
    cur: "NOK",
  },
  {
    label: "Oman",
    value: "US",
    image: "/flags/emojione_flag-for-oman.png",
    cur: "OMR",
  },
  {
    label: "Pakistan",
    value: "US",
    image: "/flags/emojione_flag-for-pakistan.png",
    cur: "PKR",
  },
  {
    label: "Palau",
    value: "US",
    image: "/flags/emojione_flag-for-palau.png",
    cur: "$",
  },
  {
    label: "Panama",
    value: "US",
    image: "/flags/emojione_flag-for-panama.png",
    cur: "USD",
  },
  {
    label: "Papua New Guinea",
    value: "US",
    image: "/flags/emojione_flag-for-papua-new-guinea.png",
    cur: "PGK",
  },
  {
    label: "Paraguay",
    value: "US",
    image: "/flags/emojione_flag-for-paraguay.png",
    cur: "₲",
  },
  {
    label: "Peru",
    value: "US",
    image: "/flags/emojione_flag-for-peru.png",
    cur: "S/",
  },
  {
    label: "Philippines",
    value: "US",
    image: "/flags/emojione_flag-for-philippines.png",
    cur: "₱",
  },
  {
    label: "Poland",
    value: "US",
    image: "/flags/emojione_flag-for-poland.png",
    cur: "PLN",
  },
  {
    label: "Portugal",
    value: "US",
    image: "/flags/emojione_flag-for-portugal.png",
    cur: "EUR",
  },
  {
    label: "Qatar",
    value: "US",
    image: "/flags/emojione_flag-for-qatar.png",
    cur: "QAR",
  },
  {
    label: "Republic of Congo",
    value: "US",
    image: "/flags/emojione_flag-for-congo-kinshasa.png",
    cur: "CFA",
  },
  {
    label: "Romania",
    value: "US",
    image: "/flags/emojione_flag-for-romania.png",
    cur: "RON",
  },
  {
    label: "Russia",
    value: "US",
    image: "/flags/emojione_flag-for-russia.png",
    cur: "RUB",
  },
  {
    label: "Reunion",
    value: "US",
    image: "/flags/emojione_flag-for-reunion.png",
    cur: "EUR",
  },
  {
    label: "Saint Kitts And Navis",
    value: "US",
    image: "/flags/emojione_flag-for-st-kitts-and-nevis.png",
    cur: "EC$",
  },
  {
    label: "Saint Lucia",
    value: "US",
    image: "/flags/emojione_flag-for-st-lucia.png",
    cur: "EC$",
  },
  {
    label: "Saint Vincent",
    value: "US",
    image: "/flags/emojione_flag-for-st-vincent-and-grenadines.png",
    cur: "EC$",
  },
  {
    label: "Samoa",
    value: "US",
    image: "/flags/emojione_flag-for-samoa.png",
    cur: "WST",
  },
  {
    label: "San Marino",
    value: "US",
    image: "/flags/emojione_flag-for-san-marino.png",
    cur: "EUR",
  },
  {
    label: "Sao Tome And Principe",
    value: "US",
    image: "/flags/emojione_flag-for-sao-tome-and-principe.png",
    cur: "STD",
  },
  {
    label: "Saudi Arabia",
    value: "US",
    image: "/flags/emojione_flag-for-saudi-arabia.png",
    cur: "SAR",
  },
  {
    label: "Senegal",
    value: "US",
    image: "/flags/emojione_flag-for-senegal.png",
    cur: "XOF",
  },
  {
    label: "Serbia",
    value: "US",
    image: "/flags/emojione_flag-for-serbia.png",
    cur: "RSD",
  },
  {
    label: "Seychelles",
    value: "US",
    image: "/flags/emojione_flag-for-seychelles.png",
    cur: "SRe",
  },
  {
    label: "Sierra Leone",
    value: "US",
    image: "/flags/emojione_flag-for-sierra-leone.png",
    cur: "SLL",
  },
  {
    label: "Singapore",
    value: "US",
    image: "/flags/emojione_flag-for-singapore.png",
    cur: "S$",
  },
  {
    label: "Slovakia",
    value: "US",
    image: "/flags/emojione_flag-for-slovakia.png",
    cur: "EUR",
  },
  {
    label: "Slovenia",
    value: "US",
    image: "/flags/emojione_flag-for-slovenia.png",
    cur: "SIT",
  },
  {
    label: "Solomon Islands",
    value: "US",
    image: "/flags/emojione_flag-for-solomon-islands.png",
    cur: "Si$",
  },
  {
    label: "Somalia",
    value: "US",
    image: "/flags/emojione_flag-for-somalia.png",
    cur: "SOS",
  },
  {
    label: "South Africa",
    value: "US",
    image: "/flags/emojione_flag-for-south-africa.png",
    cur: "ZAR",
  },
  {
    label: "South Sudan",
    value: "US",
    image: "/flags/emojione_flag-for-south-sudan.png",
    cur: "SSP",
  },
  {
    label: "Spain",
    value: "US",
    image: "/flags/emojione_flag-for-spain.png",
    cur: "ESP",
  },
  {
    label: "Sri Lanka",
    value: "US",
    image: "/flags/emojione_flag-for-sri-lanka.png",
    cur: "LKR",
  },
  {
    label: "Sudan",
    value: "US",
    image: "/flags/emojione_flag-for-sudan.png",
    cur: "SDG",
  },
  {
    label: "Suriname",
    value: "US",
    image: "/flags/emojione_flag-for-suriname.png",
    cur: "SRD",
  },
  {
    label: "Swaziland",
    value: "US",
    image: "/flags/emojione_flag-for-swaziland.png",
    cur: "SZL",
  },
  {
    label: "Sweden",
    value: "US",
    image: "/flags/emojione_flag-for-sweden.png",
    cur: "SEK",
  },
  {
    label: "Switzerland",
    value: "US",
    image: "/flags/emojione_flag-for-switzerland.png",
    cur: "CHf",
  },
  {
    label: "Syria",
    value: "US",
    image: "/flags/emojione_flag-for-syria.png",
    cur: "SYP",
  },
  {
    label: "Taiwan",
    value: "US",
    image: "/flags/emojione_flag-for-taiwan.png",
    cur: "NT$",
  },
  {
    label: "Tajikistan",
    value: "US",
    image: "/flags/emojione_flag-for-tajikistan.png",
    cur: "SM",
  },
  {
    label: "Thailand",
    value: "US",
    image: "/flags/emojione_flag-for-thailand.png",
    cur: "THB",
  },

  {
    label: "The State of Palestine",
    value: "US",
    image: "/flags/emojione_flag-for-palestine.png",
    cur: "ILS",
  },
  {
    label: "Togo",
    value: "US",
    image: "/flags/emojione_flag-for-togo.png",
    cur: "CFA",
  },
  {
    label: "Trinidad And Tobago",
    value: "US",
    image: "/flags/emojione_flag-for-trinidad-and-tobago.png",
    cur: "TT$",
  },
  {
    label: "Tunisia",
    value: "US",
    image: "/flags/emojione_flag-for-tunisia.png",
    cur: "TND",
  },
  {
    label: "Turkey",
    value: "US",
    image: "/flags/emojione_flag-for-turkey.png",
    cur: "TRY",
  },
  {
    label: "Turkmenistan",
    value: "US",
    image: "/flags/emojione_flag-for-turkmenistan.png",
    cur: "TMT",
  },
  {
    label: "Tuvalu",
    value: "US",
    image: "/flags/emojione_flag-for-tuvalu.png",
    cur: "AUD",
  },
  {
    label: "UAE",
    value: "US",
    image: "/flags/emojione_flag-for-united-arab-emirates.png",
    cur: "AED",
  },
  {
    label: "Uganda",
    value: "US",
    image: "/flags/emojione_flag-for-uganda.png",
    cur: "UGX",
  },
  {
    label: "Ukraine",
    value: "US",
    image: "/flags/emojione_flag-for-ukraine.png",
    cur: "UAH",
  },
  {
    label: "United Kingdom",
    value: "US",
    image: "/flags/emojione_flag-for-united-kingdom.png",
    cur: "GBP",
  },
  {
    label: "United State",
    value: "US",
    image: "/flags/emojione_flag-for-united-states.png",
    cur: "USD",
  },
  {
    label: "Uruguay",
    value: "US",
    image: "/flags/emojione_flag-for-uruguay.png",
    cur: "UYU",
  },
  {
    label: "Uzbekistan",
    value: "US",
    image: "/flags/emojione_flag-for-uzbekistan.png",
    cur: "UZS",
  },
  {
    label: "Vanuatu",
    value: "US",
    image: "/flags/emojione_flag-for-vanuatu.png",
    cur: "VUV",
  },
  {
    label: "Venezuela",
    value: "US",
    image: "/flags/emojione_flag-for-venezuela.png",
    cur: "VES",
  },
  {
    label: "Vietnam",
    value: "US",
    image: "/flags/emojione_flag-for-vietnam.png",
    cur: "VND",
  },
  {
    label: "Yemen",
    value: "US",
    image: "/flags/emojione_flag-for-yemen.png",
    cur: "YER",
  },
  {
    label: "Zambia",
    value: "US",
    image: "/flags/emojione_flag-for-zambia.png",
    cur: "ZMW",
  },
  {
    label: "Zimbabwe",
    value: "US",
    image: "/flags/emojione_flag-for-zimbabwe.png",
    cur: "ZWD",
  },
];
